"""Second migration.

Revision ID: 2e3b0312ff09
Revises: b696163aaabc
Create Date: 2025-04-16 00:52:48.819576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3b0312ff09'
down_revision = 'b696163aaabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queries', schema=None) as batch_op:
        batch_op.drop_column('answer')

    # ### end Alembic commands ###
