"""Initial migration.

Revision ID: b696163aaabc
Revises: 
Create Date: 2025-04-15 23:19:38.452002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b696163aaabc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_post', sa.Integer(), nullable=False),
    sa.Column('user_id_response', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_post'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_response'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    op.drop_table('users')
    # ### end Alembic commands ###
